name: Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build 🚀 & Test 🧪
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run Code Formatter
        run: pnpm run format

      - name: Run Code Linter
        run: pnpm run lint

      - name: Run Unit Tests
        run: pnpm run test:coverage

      - name: Build project
        run: pnpm run build

      - name: Install Surge cli
        run: pnpm install -g surge

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to Surge
        run: surge ./dist ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
